---
name: PE1_XZ1_7030_DMA
board: boards/mercury_zx1_pe1
version: 0.1.1

memory:
  - name: control
    offset: '0x60000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: ram_mm2s
    offset: '0x30000000'
    range: 128M
  - name: ram_s2mm
    offset: '0x38000000'
    range: 128M
  - name: dma
    offset: '0x80400000'
    range: 64K
  - name: axi_hp0
    offset: '0xF8008000'
    range: 4K
  - name: axi_hp2
    offset: '0xF800A000'
    range: 4K
  - name: ocm_mm2s
    offset: '0xFFFF0000'
    range: 32K
  - name: ocm_s2mm
    offset: '0xFFFF8000'
    range: 32K
  - name: sclr
    offset: '0xF8000000'
    range: 64K

control_registers:
  - led

status_registers:
  - forty_two

parameters:
  fclk0: 125000000 # FPGA clock speed in Hz
  fclk1: 100000000 # FPGA clock speed in Hz


drivers:
  - drivers/common.hpp
  - ../dma_example.hpp

