---
name: trenz_teb080x_te803_dma_example
board: boards/teb803
version: 0.1.1

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0

memory:
  - name: control
    offset: '0xA4001000'
    range: 4K
  - name: status
    offset: '0xA4002000'
    range: 4K
  - name: xadc
    offset: '0xA4003000'
    range: 64K
  - name: ocm_backup
    offset: '0x6FFD0000'
    range: 196K
  - name: ram_mm2s
    offset: '0x60000000'
    range: 256M
  - name: ram_s2mm
    offset: '0x70000000'
    range: 256M
  - name: dma
    offset: '0xA4010000'
    range: 64K
  - name: ocm_mm2s
    offset: '0xFFFC0000'
    range: 64K
  - name: ocm_s2mm
    offset: '0xFFFC8000'
    range: 64K
  - name: axi_m_hpm_fpd
    offset: '0xFD615000'
    range: 4K
  - name: axi_s_lpd
    offset: '0xFF9B0000'
    range: 4K
  - name: axi_s_hp0
    offset: '0xFD380000'
    range: 4K
  - name: axi_s_hp1
    offset: '0xFD390000'
    range: 4K

control_registers:
  - led

status_registers:
  - forty_two

parameters:
  fclk0: 100000000 # FPGA clock speed in Hz

xdc:
  - ./../../../boards/teb803/config/ports.xdc 
  - ./constraints.xdc

drivers:
  - server/drivers/common.hpp
  - ./dma_controller.hpp
  - ./led_blinker.hpp

web:
  - ./web/index.html
  - web/koheron.ts
  - web/led-blinker.ts
  - ./web/app.ts
  - web/main.css
