---
name: psa-quad
board: boards/alpha250-4
ersion: 0.0.1

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/edge_detector_v1_0
  - fpga/cores/comparator_v1_0
  - fpga/cores/tlast_gen_v1_0
  - fpga/cores/unrandomizer_v1_0
  - boards/alpha250/cores/precision_dac_v1_0
  - boards/alpha250/cores/spi_cfg_v1_0

memory:
  - name: control
    offset: '0x40000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: ram_s2mm_wave
    offset: '0x18000000'
    range: 64M
  - name: ram_s2mm_psa
    offset: '0x1C000000'
    range: 64M
  - name: dma_psa
    offset: '0x40400000'
    range: 64K
  - name: dma_wave
    offset: '0x40500000'
    range: 64K
  - name: axi_hp0
    offset: '0xF8008000'
    range: 4K
  - name: axi_hp2
    offset: '0xF800A000'
    range: 4K
  - name: ocm_s2mm_psa
    offset: '0xFFFF0000'
    range: 32K
  - name: ocm_s2mm_wave
    offset: '0xFFFF8000'
    range: 32K
  - name: sclr
    offset: '0xF8000000'
    range: 64K
  - name: psa0_limits
    offset: '0x43C10000'
    range: 8K
  - name: psa1_limits
    offset: '0x43C20000'
    range: 8K
  - name: psa2_limits
    offset: '0x43C30000'
    range: 8K
  - name: psa3_limits
    offset: '0x43C40000'
    range: 8K
  - name: psa4_limits
    offset: '0x43C60000'
    range: 8K
  - name: psa_module
    offset: '0x43C70000'
    range: 64K
  - name: psa_fifo
    offset: '0x43C50000'
    range: 64K

control_registers:
  - mmcm
  - precision_dac_ctl
  - precision_dac_data[2]
  - spi_cfg_data
  - spi_cfg_cmd
  - trigger_threshold
  - digital_outputs

status_registers:
  - spi_cfg_sts
  - adc0[n_adc]
  - adc1[n_adc]
  - digital_inputs
  - adc_freq[n_adc]
  - psa_runtime 

parameters:
  fclk0: 125000000
  adc_clk: 250000000
  adc_width: 16
  n_adc: 2

    

xdc:
  - boards/alpha250-4/config/ports.xdc
  - ./constraints.xdc

drivers:
  - boards/alpha250-4/drivers/common.hpp
  - boards/alpha250/drivers/eeprom.hpp
  - boards/alpha250/drivers/gpio-expander.hpp
  - boards/alpha250/drivers/temperature-sensor.hpp
  - boards/alpha250/drivers/power-monitor.hpp
  - boards/alpha250-4/drivers/clock-generator.hpp
  - boards/alpha250-4/drivers/ltc2157.hpp
  - boards/alpha250/drivers/ad9747.hpp
  - boards/alpha250/drivers/precision-adc.hpp
  - boards/alpha250/drivers/precision-dac.hpp
  - boards/alpha250/drivers/spi-config.hpp
  - ./DmaSGDriver.hpp
  - ./PSAcore.hpp

web:
  - web/index.html
  - web/main.css
  - web/koheron.ts
