---
name: adc-dma-orig
board: boards/alpha250-4
version: 0.1.2

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0
  - fpga/cores/latched_mux_v1_0
  - fpga/cores/edge_detector_v1_0
  - fpga/cores/unrandomizer_v1_0
  - fpga/cores/comparator_v1_0
  - fpga/cores/tlast_gen_v1_0
  - fpga/cores/bus_multiplexer_v1_0
  - boards/alpha250/cores/precision_dac_v1_0
  - boards/alpha250/cores/spi_cfg_v1_0

memory:
  - name: ps_status
    offset: '0x58000000'
    range: 4K
  - name: control
    offset: '0x40000000'
    range: 4K
  - name: status
    offset: '0x50000000'
    range: 4K
  - name: xadc
    offset: '0x43C00000'
    range: 64K
  - name: ram_s2mm0
    offset: '0x1E000000'
    range: 16M
  - name: ram_s2mm1
    offset: '0x1F000000'
    range: 16M
  - name: dma0
    offset: '0x40400000'
    range: 64K
  - name: dma1
    offset: '0x40500000'
    range: 64K
  - name: axi_hp0
    offset: '0xF8008000'
    range: 4K
  - name: axi_hp2
    offset: '0xF800A000'
    range: 4K
  - name: ocm_s2mm0
    offset: '0xFFFF0000'
    range: 32K
  - name: ocm_s2mm1
    offset: '0xFFFF8000'
    range: 32K
  - name: sclr
    offset: '0xF8000000'
    range: 64K
  - name: ps_control
    offset: '0x54000000'
    range: 4K

control_registers:
  - mmcm
  - precision_dac_ctl
  - precision_dac_data[2]
  - digital_outputs
  - channel_select

status_registers:
  - adc0[n_adc]
  - adc1[n_adc]
  - digital_inputs

ps_control_registers:
  - spi_cfg_data
  - spi_cfg_cmd

ps_status_registers:
  - spi_cfg_sts

parameters:
  fclk0: 143000000
  adc_clk: 250000000
  adc_width: 16
  n_adc: 2

xdc:
  - boards/alpha250-4/config/ports.xdc

drivers:
  - boards/alpha250-4/drivers/common.hpp
  - boards/alpha250/drivers/eeprom.hpp
  - boards/alpha250/drivers/gpio-expander.hpp
  - boards/alpha250/drivers/temperature-sensor.hpp
  - boards/alpha250/drivers/power-monitor.hpp
  - boards/alpha250-4/drivers/clock-generator.hpp
  - boards/alpha250-4/drivers/ltc2157.hpp
  - boards/alpha250/drivers/ad9747.hpp
  - boards/alpha250/drivers/precision-adc.hpp
  - boards/alpha250/drivers/precision-dac.hpp
  - boards/alpha250/drivers/spi-config.hpp
  - ./adc-dma.hpp

web:
  - web/index.html
  - web/main.css
  - web/koheron.ts
