
set_property IOSTANDARD LVCMOS33 [get_ports ANIOS_A*]
set_property -dict {PACKAGE_PIN G10} [get_ports {ANIOS_A_CLK[0]}]
set_property -dict {PACKAGE_PIN F10} [get_ports {ANIOS_A_CLK[1]}]
set_property -dict {PACKAGE_PIN H12} [get_ports {ANIOS_A[0]}]
set_property -dict {PACKAGE_PIN G11} [get_ports {ANIOS_A[1]}]
set_property -dict {PACKAGE_PIN J12} [get_ports {ANIOS_A[2]}]
set_property -dict {PACKAGE_PIN H11} [get_ports {ANIOS_A[3]}]
set_property -dict {PACKAGE_PIN J11} [get_ports {ANIOS_A[4]}]
set_property -dict {PACKAGE_PIN J10} [get_ports {ANIOS_A[5]}]
set_property -dict {PACKAGE_PIN K13} [get_ports {ANIOS_A[6]}]
set_property -dict {PACKAGE_PIN K12} [get_ports {ANIOS_A[7]}]
set_property -dict {PACKAGE_PIN G13} [get_ports {ANIOS_A[8]}]
set_property -dict {PACKAGE_PIN F13} [get_ports {ANIOS_A[9]}]
set_property -dict {PACKAGE_PIN A12} [get_ports {ANIOS_A[10]}]
set_property -dict {PACKAGE_PIN A11} [get_ports {ANIOS_A[11]}]
set_property -dict {PACKAGE_PIN C12} [get_ports {ANIOS_A[12]}]
set_property -dict {PACKAGE_PIN B11} [get_ports {ANIOS_A[13]}]
set_property -dict {PACKAGE_PIN B10} [get_ports {ANIOS_A[14]}]
set_property -dict {PACKAGE_PIN A10} [get_ports {ANIOS_A[15]}]
set_property -dict {PACKAGE_PIN D11} [get_ports {ANIOS_A[16]}]
set_property -dict {PACKAGE_PIN C11} [get_ports {ANIOS_A[17]}]
set_property -dict {PACKAGE_PIN E10} [get_ports {ANIOS_A[18]}]
set_property -dict {PACKAGE_PIN D10} [get_ports {ANIOS_A[19]}]
set_property -dict {PACKAGE_PIN E12} [get_ports {ANIOS_A[20]}]
set_property -dict {PACKAGE_PIN D12} [get_ports {ANIOS_A[21]}]
set_property -dict {PACKAGE_PIN E14} [get_ports {ANIOS_A[22]}]
set_property -dict {PACKAGE_PIN E13} [get_ports {ANIOS_A[23]}]

set_property IOSTANDARD LVCMOS33 [get_ports ANIOS_B*]
set_property -dict {PACKAGE_PIN F12} [get_ports {ANIOS_B_CLK[0]}]
set_property -dict {PACKAGE_PIN F11} [get_ports {ANIOS_B_CLK[1]}]
set_property -dict {PACKAGE_PIN K14} [get_ports {ANIOS_B[0]}]
set_property -dict {PACKAGE_PIN J14} [get_ports {ANIOS_B[1]}]
set_property -dict {PACKAGE_PIN K15} [get_ports {ANIOS_B[2]}]
set_property -dict {PACKAGE_PIN J15} [get_ports {ANIOS_B[3]}]
set_property -dict {PACKAGE_PIN G15} [get_ports {ANIOS_B[4]}]
set_property -dict {PACKAGE_PIN G14} [get_ports {ANIOS_B[5]}]
set_property -dict {PACKAGE_PIN F15} [get_ports {ANIOS_B[6]}]
set_property -dict {PACKAGE_PIN E15} [get_ports {ANIOS_B[7]}]
set_property -dict {PACKAGE_PIN C14} [get_ports {ANIOS_B[8]}]
set_property -dict {PACKAGE_PIN C13} [get_ports {ANIOS_B[9]}]
set_property -dict {PACKAGE_PIN B15} [get_ports {ANIOS_B[10]}]
set_property -dict {PACKAGE_PIN A15} [get_ports {ANIOS_B[11]}]
set_property -dict {PACKAGE_PIN B14} [get_ports {ANIOS_B[12]}]
set_property -dict {PACKAGE_PIN A14} [get_ports {ANIOS_B[13]}]
set_property -dict {PACKAGE_PIN B13} [get_ports {ANIOS_B[14]}]
set_property -dict {PACKAGE_PIN A13} [get_ports {ANIOS_B[15]}]
set_property -dict {PACKAGE_PIN H14} [get_ports {ANIOS_B[16]}]
# shared with Dip 0
set_property -dict {PACKAGE_PIN H13} [get_ports {ANIOS_B[17]}]
# shared with Dip 1
set_property -dict {PACKAGE_PIN AG4} [get_ports {ANIOS_B[20]}]
#shared with btn 0
set_property -dict {PACKAGE_PIN AJ1} [get_ports {ANIOS_B[21]}]
#shared with btn 1
set_property -dict {PACKAGE_PIN AH11} [get_ports {ANIOS_B[22]}]
#shared with btn 2
set_property -dict {PACKAGE_PIN AG9} [get_ports {ANIOS_B[23]}]
#shared with btn 3
