set_property -dict [list \
  CONFIG.PSU__PRESET_APPLIED {1} \
  CONFIG.PSU_BANK_0_IO_STANDARD {LVCMOS18} \
  CONFIG.PSU_BANK_1_IO_STANDARD {LVCMOS33} \
  CONFIG.PSU_BANK_2_IO_STANDARD {LVCMOS18} \
  CONFIG.PSU_BANK_3_IO_STANDARD {LVCMOS18} \
  CONFIG.PSU__PSS_REF_CLK__FREQMHZ {33.333333} \
  CONFIG.PSU__QSPI__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__QSPI__PERIPHERAL__MODE {Dual Parallel} \
  CONFIG.PSU__QSPI__PERIPHERAL__DATA_MODE {x4} \
  CONFIG.PSU__QSPI__GRP_FBCLK__ENABLE {1} \
  CONFIG.PSU__TTC0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__TTC1__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__TTC2__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__TTC3__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__SWDT0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__SWDT1__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__DDRC__CL {16} \
  CONFIG.PSU__DDRC__CWL {14} \
  CONFIG.PSU__DDRC__BG_ADDR_COUNT {2} \
  CONFIG.PSU__DDRC__DEVICE_CAPACITY {8192 MBits} \
  CONFIG.PSU__DDRC__DRAM_WIDTH {8 Bits} \
  CONFIG.PSU__DDRC__ROW_ADDR_COUNT {16} \
  CONFIG.PSU__DDRC__SPEED_BIN {DDR4_2133P} \
  CONFIG.PSU__DDRC__T_RC {48} \
  CONFIG.PSU__DDRC__T_RCD {17} \
  CONFIG.PSU__DDRC__T_RP {17} \
  CONFIG.PSU__DDRC__DDR4_T_REF_MODE {1} \
  CONFIG.PSU__DDRC__COMPONENTS {UDIMM} \
  CONFIG.PSU__CRF_APB__DDR_CTRL__FREQMHZ {1066} \
  CONFIG.PSU__DDRC__T_RAS_MIN {33.0} \
  CONFIG.PSU__UART0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__UART0__PERIPHERAL__IO {MIO 42 .. 43} \
  CONFIG.PSU__PJTAG__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__PJTAG__PERIPHERAL__IO {MIO 26 .. 29} \
  CONFIG.PSU__SD0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__SD0__SLOT_TYPE {eMMC} \
  CONFIG.PSU__SD0__DATA_TRANSFER_MODE {8Bit} \
  CONFIG.PSU__SD0__PERIPHERAL__IO {MIO 13 .. 22} \
  CONFIG.PSU__SD0__RESET__ENABLE {1} \
  CONFIG.PSU__SD0__GRP_POW__IO {MIO 23} \
  CONFIG.PSU__SD1__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__SD1__SLOT_TYPE {SD 2.0} \
  CONFIG.PSU__SD1__PERIPHERAL__IO {MIO 46 .. 51} \
  CONFIG.PSU__SD1__GRP_CD__ENABLE {1} \
  CONFIG.PSU__SD1__GRP_CD__IO {MIO 45} \
  CONFIG.PSU__SD1__GRP_WP__ENABLE {1} \
  CONFIG.PSU__SD1__GRP_WP__IO {MIO 44} \
  CONFIG.PSU_MIO_44_PULLUPDOWN {disable} \
  CONFIG.PSU_MIO_44_INPUT_TYPE {cmos} \
  CONFIG.PSU_MIO_45_PULLUPDOWN {disable} \
  CONFIG.PSU_MIO_45_INPUT_TYPE {cmos} \
  CONFIG.PSU_MIO_46_PULLUPDOWN {disable} \
  CONFIG.PSU_MIO_46_INPUT_TYPE {cmos} \
  CONFIG.PSU_MIO_47_PULLUPDOWN {disable} \
  CONFIG.PSU_MIO_47_INPUT_TYPE {cmos} \
  CONFIG.PSU_MIO_48_PULLUPDOWN {disable} \
  CONFIG.PSU_MIO_48_INPUT_TYPE {cmos} \
  CONFIG.PSU_MIO_49_PULLUPDOWN {disable} \
  CONFIG.PSU_MIO_49_INPUT_TYPE {cmos} \
  CONFIG.PSU_MIO_50_PULLUPDOWN {disable} \
  CONFIG.PSU_MIO_50_INPUT_TYPE {cmos} \
  CONFIG.PSU_MIO_51_PULLUPDOWN {disable} \
  CONFIG.PSU__CAN0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__CAN0__PERIPHERAL__IO {MIO 34 .. 35} \
  CONFIG.PSU__I2C0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__I2C0__PERIPHERAL__IO {MIO 38 .. 39} \
  CONFIG.PSU__ENET3__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__ENET3__PERIPHERAL__IO {MIO 64 .. 75} \
  CONFIG.PSU__ENET3__GRP_MDIO__ENABLE {1} \
  CONFIG.PSU__ENET3__GRP_MDIO__IO {MIO 76 .. 77} \
  CONFIG.PSU__PCIE__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__PCIE__PERIPHERAL__ENDPOINT_IO {MIO 33} \
  CONFIG.PSU__PCIE__PERIPHERAL__ROOTPORT_IO {MIO 33} \
  CONFIG.PSU__PCIE__MAXIMUM_LINK_WIDTH {x1} \
  CONFIG.PSU__PCIE__LANE0__IO {GT Lane0} \
  CONFIG.PSU__PCIE__DEVICE_PORT_TYPE {Root Port} \
  CONFIG.PSU__PCIE__DEVICE_ID {0xD021} \
  CONFIG.PSU__PCIE__CLASS_CODE_SUB {0x04} \
  CONFIG.PSU__USB0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__USB0__PERIPHERAL__IO {MIO 52 .. 63} \
  CONFIG.PSU__USB3_0__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__USB3_0__PERIPHERAL__IO {GT Lane1} \
  CONFIG.PSU__DP__LANE_SEL {Dual Higher} \
  CONFIG.PSU__DISPLAYPORT__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__DISPLAYPORT__LANE0__IO {GT Lane3} \
  CONFIG.PSU__DISPLAYPORT__LANE1__IO {GT Lane2} \
  CONFIG.PSU__CRF_APB__DP_VIDEO_REF_CTRL__SRCSEL {VPLL} \
  CONFIG.PSU__CRF_APB__GPU_REF_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRF_APB__GDMA_REF_CTRL__SRCSEL {APLL} \
  CONFIG.PSU__CRF_APB__DPDMA_REF_CTRL__SRCSEL {APLL} \
  CONFIG.PSU__USB0__REF_CLK_SEL {Ref Clk1} \
  CONFIG.PSU__USB0__REF_CLK_FREQ {100} \
  CONFIG.PSU__DP__REF_CLK_SEL {Ref Clk2} \
  CONFIG.PSU__PCIE__REF_CLK_SEL {Ref Clk0} \
  CONFIG.PSU__GPIO0_MIO__PERIPHERAL__ENABLE {1} \
  CONFIG.PSU__CRF_APB__DP_AUDIO_REF_CTRL__SRCSEL {RPLL} \
  CONFIG.PSU__CRF_APB__DP_STC_REF_CTRL__SRCSEL {RPLL} \
  CONFIG.PSU__CRF_APB__TOPSW_MAIN_CTRL__SRCSEL {APLL} \
  CONFIG.PSU__CRL_APB__CPU_R5_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRL_APB__SDIO0_REF_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRL_APB__SDIO1_REF_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRL_APB__ADMA_REF_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRL_APB__IOU_SWITCH_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRL_APB__LPD_SWITCH_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRL_APB__PL0_REF_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRL_APB__PL1_REF_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRL_APB__PL2_REF_CTRL__SRCSEL {IOPLL} \
  CONFIG.PSU__CRL_APB__PL3_REF_CTRL__SRCSEL {IOPLL} \
] [get_bd_cells $ps_name]
